creativecommons/legaldb

jekyll/_config.yml, jekyll/index.html
Fixes #13
**Description**
- Updated the title and name in texts, from Creative Commons Case Law Database to "Creative Commons Legal Database" and CC case Law Database to "CC Legal Database" .
- Updated the URL (or redirect), the title on all pages, and text throughout to reflect the renaming.
**Checklist:**
index.md`).
Version 1.1
Suite D4700
By making a contribution to this project, I certify …
=> Update header, text name and URL to Creative Commons Legal Database.

README.md
Fixes #18 
The Form Responses Google Spreadsheet link is restricted to the public. So mentioned it in the README, as discussed here in this comment: https://github.com/creativecommons/caselaw/issues/18#issuecomment-603956238
index.md`).
```
Version 1.1
Suite D4700
have the …
```
=> Mention Links with Restricted Access in README

README.md
Added soon to be re-implemented for user bouncing in here
index.md`).
```
Version 1.1
Suite D4700
indicated in the file; or
(b) The contribution is based upon previous work that, to the best
of my knowledge, is covered under an …
```
=> Added "soon to be re-implemented".

README.md
moved and updated potential internship project warning.
See rendered README at https://github.com/creativecommons/caselaw/blob/pending-project/README.md
index.md`).
<details>
```
Version 1.1
Suite D4700
have the right to …
```
=> moved and updated potential internship project warning

.cc-metadata.yml
This adds slack channel name as proposed in [PR: 243 in creativecommons.github.io-source](https://github.com/creativecommons/creativecommons.github.io-source/pull/243)
for [Issue: 241 in creativecommons.github.io-source](https://github.com/creativecommons/creativecommons.github.io-source/issues/241)
PRs like this would have to be made for all repos with a slack channel to reflect on the projects page.
index.md`).
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and distribute …
```
=> Add slack channel for the repo in metadata

.cc-metadata.yml, .github/CODEOWNERS
After check the [Repo Guidelines](https://opensource.creativecommons.org/contributing-code/github-repo-guidelines/) these are some changes to keep base files in sync.
Additional Items (CI, linters, test) will be added later.
<details>
```
Version 1.1
Suite D4700 …
```
=> Add CC metadata and team to CODEOWNERS

legal_db/admin.py, legal_db/static/styles.scss, legal_db/templates/legal_db/base.html, legal_db/templates/legal_db/faq.html, legal_db/templates/legal_db/index.html, legal_db/templates/legal_db/partials/_search.html, legal_db/templates/legal_db/scholarship/index.html, legal_db/urls.py, legal_db/views.py
Makes the Home page design according to the Figma [mockup](https://www.figma.com/file/L2sACqzX61N2OMd5lmisop/Caselaw-Mockups?node-id=335%3A2118).
https://caselaw-mirr-feature-ho-mcws7n.herokuapp.com/
index.md`).
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in …
```
=> Homepage design

legal_db/admin.py, legal_db/static/styles.scss, legal_db/templates/404.html, legal_db/templates/legal_db/base.html, legal_db/templates/legal_db/case/index.html, legal_db/templates/legal_db/faq.html, legal_db/templates/legal_db/index.html, legal_db/templates/legal_db/partials/_search.html, legal_db/templates/legal_db/scholarship/index.html, legal_db/urls.py, legal_db/views.py
This PR creates the 404 error page template.
Visit a random non-existing page, for example https://caselaw-mirr-feature-40-bkebri.herokuapp.com/asdf
index.md`).
<details>
```
Version 1.1
Suite D4700
have the right to …
```
=> Add 404 error page

legal_db/static/app.js, legal_db/templates/legal_db/base.html, legal_db/templates/legal_db/case/detail.html, legal_db/templates/legal_db/case/index.html, legal_db/templates/legal_db/index.html, legal_db/templates/legal_db/partials/_search.html, legal_db/templates/legal_db/scholarship/detail.html, legal_db/templates/legal_db/scholarship/index.html, legal_db/views.py
This enable to filter rows (for both cases and scholarships) by topics related. On list pages, multiple tags can be selected and any row with at least one tag associated will be shown, this can be combined will search terms. In Home and detail pages the links of each tag were added too.
See https://caselaw-mirr-feature-fi-9uj0zf.herokuapp.com/
index.md`).
<details>
```
Version 1.1
Suite D4700
license document, but changing it is …
```
=> Filtering by tags

legal_db/templates/legal_db/case/detail.html, legal_db/templates/legal_db/scholarship/detail.html
Fixes #53 by @panchovm
Fix spacing for both case and scholarship detail pages.
index.md`).
<details>
```
Version 1.1
Suite D4700
indicated in the file; or
(b) The …
```
=> Increase space between titles and descriptions

README.md
Clarified Work in Progress warning to be accurate and more helpful
See it on branch [README.md](https://github.com/creativecommons/caselaw/blob/wip-warning/README.md)
index.md`).
<details>
```
Version 1.1
Suite D4700
have …
```
=> Updated WIP Warning

legal_db/static/styles.scss, legal_db/templates/legal_db/case/detail.html, legal_db/templates/legal_db/case/index.html, legal_db/templates/legal_db/faq.html, legal_db/templates/legal_db/index.html, legal_db/templates/legal_db/scholarship/detail.html, legal_db/templates/legal_db/scholarship/index.html
Fixes #42 by @panchovm
Fixes #43 by @panchovm
Fixes #52 by @panchovm
Fixes #54 by @panchovm
Restructure site components and change styles to correct alignment.
See https://caselaw-mirr-bugfix-con-aldm6d.herokuapp.com/
index.md`).
<details>
```
Version 1.1
Suite D4700
(a) The …
```
=> Fix content alignment of the site

legal_db/static/listing.js, legal_db/static/styles.scss, legal_db/templates/legal_db/case/index.html, legal_db/templates/legal_db/scholarship/index.html
Related to #48 by @panchovm.
Fix color and **submit the search form** (in `/cases` and `/scholarship`) **at click on any tag**, this to get instant reaction as discussed [here](https://github.com/creativecommons/caselaw/pull/41#issuecomment-672926413).
See https://caselaw-mirr-bugfix-hov-moea0h.herokuapp.com/
index.md`).
<details>
```
Version 1.1
Suite D4700
Developer's …
```
=> Fix color on hover state of scholarship buttons/cards and filter tags reaction

.github/workflows/main.yml, caselaw/settings.py
Fixes #76 by me.
Remove the github secret variable and add a custom key just for github workflow.
index.md`).
<details>
```
Version 1.1
Suite D4700
indicated in the …
```
=> Remove github secret variable

legal_db/templates/legal_db/scholarship/form.html
Fix labels appearance on scholarship form
index.md`).
<details>
```
Version 1.1
Suite D4700
indicated in the file; or
(b) The contribution is based upon previous …
```
=> Scholarship form

legal_db/static/styles.scss, legal_db/templates/legal_db/case/form.html, legal_db/templates/legal_db/scholarship/form.html, legal_db/templates/legal_db/scholarship/index.html
Fixes #55 by @panchovm.
Left-align title with navbar logo and center the form.
See:
- [Case form](https://caselaw-mirr-bugfix-for-fd6xdu.herokuapp.com/cases/submit/)
- [Scholarship form](https://caselaw-mirr-bugfix-for-fd6xdu.herokuapp.com/scholarship/submit/)
index.md`).
<details>
```
Version 1.1
Suite D4700
By making a contribution to this project, I …
```
=> Correct alignment of form pages

legal_db/admin.py
A few pending changes. Tweaks Django admin to make some improvements:
- Add filtering and search input on case and scholarship lists.
- Enable changing the order of FAQs
- Custom order of fields in edit forms
See https://caselaw-mirr-improvemen-wlltrx.herokuapp.com/
index.md`).
<details>
```
Version 1.1
Suite D4700
By making a contribution to …
```
=> Customize admin panel

legal_db/static/styles.scss, legal_db/templates/legal_db/base.html, legal_db/templates/legal_db/index.html, legal_db/templates/legal_db/partials/_footer.html
Fixes #47 by @panchovm.
This changes the FAQ link on Home page to use a `LinkBorder` component, as shown in the [Design Library](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=776%3A0&viewport=-4223%2C-277%2C0.7863361239433289).
It aslo adds a link to Home in the footer.
- Update Vocabulary version
- Update main colors values: Tomato and Forest Green.
See https://caselaw-mirr-feature-li-a5l7yp.herokuapp.com/
index.md`).
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy …
```
=> Link border card for FAQ link

README.md
- updated README to prepare for production deployment of django site
- Existing [README](https://github.com/creativecommons/caselaw/blob/main/README.md)
- Proposed [README](https://github.com/creativecommons/caselaw/blob/readme-pre-prod/README.md)
index.md`).
- N/A I added tests for the changes I made (if applicable).
<details>
```
Version 1.1
Suite D4700
Developer's Certificate …
```
=> updated README to prepare for production deployment of django site

README.md, deploy_to_heroku.md
Part of https://github.com/creativecommons/tech-support/issues/692 (private repo)
- Add Deploy to Heroku documentation
- Review it at: https://github.com/creativecommons/caselaw/blob/deploy-to-heroku/deploy_to_heroku.md
- Thank you for doing most of the work @krysal !
index.md`).
<details>
```
Version 1.1
Suite D4700
By making a contribution …
```
=> Add Deploy to Heroku documentation

README.md
- updated name & description. removed legacy info
- [New README](https://github.com/creativecommons/legaldb/blob/readme-prod-update/README.md)
- [Old/Current README](https://github.com/creativecommons/legaldb/blob/main/README.md)
- part of https://github.com/creativecommons/tech-support/issues/693 (private repo)
index.md`).
<details>
```
Version 1.1
Suite D4700
Developer's …
```
=> updated name & description. removed legacy info

README.md
Fixes #102 by @pratikdaigavane 
Updated the command to:  `docker-compose run app sh -c "python manage.py createsuperuser"`
index.md`).
<details>
```
Version 1.1
Suite D4700
have the right to submit it under the open source …
```
=> Fix Typo in Create Super User command

Dockerfile, Pipfile, Pipfile.lock, README.md, caselaw/settings.py
- Update to use Python 3.9
> By default, newly created Python apps use the python-3.9.5 runtime.
([Heroku Python Support | Heroku Dev Center](https://devcenter.heroku.com/articles/python-support#specifying-a-python-version))
- Add `gettext` to Docker configuration to support future translation work
- Simplify docker commands and de-emphasize pipenv in README
index.md`).
<details>
```
Version 1.1
Suite D4700
license document, but …
```
=> use Python 3.9

legal_db/views.py
Fixes #119 
- #119 
Expand search fields
- Cases search (filter) fields added:
- country
- license
- decision_year
- Scholarship search (filter) fields added:
- publication_year
- license
- [Search | Django documentation | Django](https://docs.djangoproject.com/en/3.2/topics/db/search/)
index.md`).
<details>
```
Version 1.1
Suite …
```
=> expand search fields

Pipfile.lock, README.md, deploy_to_heroku.md, webpack/package-lock.json
Fixes #125
Update Python and JavaScript dependencies
npm update output:
```
removed 1 package, changed 20 packages, and audited 166 packages in 7s
24 packages are looking for funding
run `npm fund` for details
```
index.md`).
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and distribute …
```
=> Update Python and JavaScript dependencies

Pipfile, Pipfile.lock
Python and tests updates
- [NVD - CVE-2022-28347](https://nvd.nist.gov/vuln/detail/CVE-2022-28347)
- [CWE - CWE-89: Improper Neutralization of Special Elements used in an SQL Command ('SQL Injection') (4.7)](https://cwe.mitre.org/data/definitions/89.html)
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```
=> Python updates

.github/workflows/main.yml, Dockerfile, Pipfile, docker-compose.yml
- Update Docker, GitHub Actions, and Pipfile Python version to match Heroku default (`3.10`)
- Update Docker and GitHub Actions PostgreSQL image version to match Heroku default (`14`)
- Update GitHub Actions packages to latest:
- ~~actions/checkout@v2~~ => actions/checkout@v3
- [actions/checkout](https://github.com/actions/checkout): Action for checking out a repo
- ~~actions/setup-python@v2~~ => actions/setup-python@v4
- [actions/setup-python](https://github.com/actions/setup-python): Set up your GitHub Actions workflow with a specific version of Python
- ~~actions/upload-artifact@master~~ => actions/upload-artifact@v3
- [actions/upload-artifact](https://github.com/actions/upload-artifact): This uploads artifacts from your workflow allowing you to share data between jobs and store data …
=> update GitHub Actions package, PostgreSQL image, and Python version

Pipfile.lock, webpack/package-lock.json
Fixes #130 
- Update JavaScript/NPM packages
```
added 8 packages, removed 11 packages, changed 30 packages, and audited 163 packages in 6s
```
- Update Python packages
```diff
--- piplist.old	2022-08-10 09:54:09.000000000 -0700
+++ piplist.new	2022-08-10 09:54:09.000000000 -0700
@@ -1,53 +1,48 @@
Package              Version
asgiref              3.5.2
black                22.6.0
certifi              2022.6.15
click                8.1.3
-distlib              0.3.4
-dj-database-url      0.5.0
-Django               3.2.14
+distlib              0.3.5
+dj-database-url      1.0.0
+Django               3.2.15
django-appconf       1.0.5
-django-compressor    4.0
+django-compressor    4.1
django-countries     7.3.2
django-heroku        0.3.1
django-libsass       0.9
django-markdownx     3.0.1 …
```
=> Update JavaScript/NPM and Python packages

.github/workflows/main.yml, Pipfile, Pipfile.lock
Fixes https://github.com/advisories/GHSA-qrw5-5h28-6cmg
- correct and improve GitHub Actions workflow
- [failure - Expressions - Learn GitHub Actions - GitHub Docs](https://docs.github.com/en/actions/learn-github-actions/expressions#failure)
- update python modules:
```diff
--- piplist.old	2022-10-19 08:47:39.000000000 -0700
+++ piplist.new	2022-10-19 08:47:39.000000000 -0700
@@ -3 +3 @@
-black                22.6.0
+black                22.10.0
@@ -8 +8 @@
-Django               3.2.15
+Django               3.2.16
@@ -11 +11 @@
-django-countries     7.3.2
+django-countries     7.4.2
@@ -19 +19 @@
-Faker                13.15.1
+Faker                15.1.1
@@ -28 +28 @@
-pathspec             0.9.0
+pathspec             0.10.1
@@ -33 +33 @@
-psycopg2             2.9.3
+psycopg2 …
```
=> update python modules

legal_db/templates/legal_db/partials/_footer.html
Fixes #146  by @justaskulkarni
Resolution:
The problematic part in the code:
Changes:
Use of Bulma to fix responsiveness
index.md`).
<details>
```
Version 1.1
Suite D4700
Developer's …
```
=> Fixed Footer Responsiveness

legal_db/templates/legal_db/case/form.html
Fixes #149 by @justaskulkarni 
There is no margin between the 'Add Link' and 'Submit Case' buttons.
Add Link buttons is aligned to the right and therefore, it doesn't cause an issue on larger screens.
However on smaller screens, the lack of a margin is clearly noticeable.
**Cause of the Error**
When the is-pulled-right class is removed, we obtain the desired spacing.
However, as expected, the 'Add Link' is no longer aligned to the right.
**Course of Action**
Identified a way to align the 'Add Link' button to the right without the use of is-pulled-right class.
**Solution**
buttons.is-right can be used to align the 'Add Link' button to the right.
https://user-images.githubusercontent.com/98650743/230157490-ea6d7dcf-c6db-4874-9c18-fab708b07698.mp4
index.md`). …
=> Added spacing between ADD LINK and SUBMIT CASE buttons

webpack/package-lock.json
Fixes #148, fixes #160
- #148 
- 🟠 [Cross-realm object access in Webpack 5 · CVE-2023-28154 · GitHub Advisory Database](https://github.com/advisories/GHSA-hc6q-2mpp-qw7j)
- #160 
- 🟡 [semver vulnerable to Regular Expression Denial of Service · CVE-2022-25883 · GitHub Advisory Database](https://github.com/advisories/GHSA-c2qf-rxjj-qqgw)
- 🟡 [PostCSS line return parsing error · CVE-2023-44270 · GitHub Advisory Database](https://github.com/advisories/GHSA-7fh5-64p2-3v2j)
update npm packages
```
added 3 packages, removed 1 package, changed 59 packages, and audited 165 packages in 6s
24 packages are looking for funding
run `npm fund` for details
found 0 vulnerabilities
```
index.md`).
For the …
=> update npm packages

caselaw/settings.py
- update Django documentation URLs to 4.2
- (should have been included in #177)
- no functional changes
- each of the new links resolves as expected
index.md`).
<details>
```
Version 1.1
Suite D4700
license document, but changing it is not …
```
=> update Django documentation URLs to 4.2

.github/workflows/main.yml, Dockerfile, docker-compose.yml
- improve `Dockerfile` layout to better align with best practices and reduce the number of layers
- upgrade to postgres 15 and improve feedback/documentation in `docker-compose.yml`
- https://docs.docker.com/build/building/best-practices/
- https://docs.docker.com/compose/environment-variables/variable-interpolation/
- https://devcenter.heroku.com/articles/heroku-postgres-version-support
command:
```shell
docker compose exec app ./manage.py test
```
output excerpt:
```
Ran 13 tests in 1.562s
OK
```
index.md`).
For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent to "open content license or public domain …
=> Update docker configs and postges version

legal_db/templates/legal_db/index.html
correct spelling error
index.md`).
<details>
```
Version 1.1
Suite D4700
(a) The contribution …
```
=> correct spelling error

README.md
- Fixes #153 by @Xaid-vfx
Added command for cloning, updated docs to include git documentation for first time users.
index.md`).
<details>
```
Version 1.1
Suite D4700
Developer's Certificate …
```
=> Update README.md to include beginner documentation.

.gitignore, legal_db/templates/legal_db/case/form.html, legal_db/templates/legal_db/index.html
- Fixes #217
This pull request addresses two issues:
1. It fixes inconsistent use of quotation marks in the `{% url %}` tags in the Django templates by standardizing them to single quotes.
2. It normalizes unusual line terminator characters in `form.html`.
No major technical changes were made beyond the quoted changes and line terminators normalization. All affected files have been updated accordingly.
I ran the test suite after making these changes, and all tests passed successfully.
index.md`). …
=> Fix inconsistent quotation marks in Django  tags, normalize line terminators (#217)

.gitignore, legal_db/templates/legal_db/base.html
- Fixes #213  by @Silvia-Wachira
This pull request adds meta tags for keywords and author to improve the SEO of CC's Legal DB webiste.
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```
=> Added Meta Tags for keyword and author

legal_db/templates/legal_db/base.html
- Fixes #220 by @SisiVero
The "media" attribute was missing from the "link" tag in the stylesheet, as required by the vocabulary documentation. This pull request has fixed the issue, and now the base.html file in the legaldb directory complies with the requirements outlined in the Vocabulary documentation. 
index.md`).
<details>
```
Version 1.1
1 …
```
=> Updated the stylesheet of the base.html file to include  'media=all' as per the Vocabulary documentation.

.env.template, README.md
- Fixes #200 by @FatumaA
Replaces #202 (Git issues)
Adds more explicit instructions in the README and adds clearer comments in the `.env.template` file.
index.md`).
<details>
```
Version 1.1
Suite D4700
license document, but changing it is …
```
=> Enhancement: Make env template and README more explicit

Pipfile, Pipfile.lock
- 🟠 [Django SQL injection in HasKey(lhs, rhs) on Oracle · CVE-2024-53908 · GitHub Advisory Database](https://github.com/advisories/GHSA-m9g8-fxxm-xg86)
- 🟡 [Django denial-of-service in django.utils.html.strip_tags() · CVE-2024-53907 · GitHub Advisory Database
](https://github.com/advisories/GHSA-8498-2h75-472j)
- Update Python modules (Django 4.2.17, etc.)
- ⚠️ **Requires docker images to be rebuilt (`docker compose build`)**
```shell
git checkout main
docker compose up
docker compose exec app pip list > piplist.old
docker compose down
git checkout -b update-python
pipenv update --dev
docker compose build
docker compose up
docker compose exec app pip list > piplist.new
docker compose down
gsed -e'/^---/d' -i piplist.*
diff -u piplist.old piplist.new
```
```diff
--- piplist.old	2025-01-08 …
```
=> Update Python modules (Django 4.2.17, etc.)
